import type { Metadata } from 'next'
import { headers } from 'next/headers'
import './globals.css'

import { cookieToInitialState } from 'wagmi'

import Web3ModalProvider from '@/context/web3'
import { config } from '@/utils/web3'


import { ToastContainer } from 'react-toastify'
import "react-toastify/dist/ReactToastify.css"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body>
        <Web3ModalProvider initialState={initialState}>
          {children}
        </Web3ModalProvider>
        <ToastContainer />
      </body>
    </html>
  )
}